/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FuelRouteImport } from './routes/fuel'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FuelRoute = FuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/drivers': typeof DriversRoute
  '/fleet': typeof FleetRoute
  '/fuel': typeof FuelRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/signup': typeof SignupRoute
  '/trips': typeof TripsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/drivers': typeof DriversRoute
  '/fleet': typeof FleetRoute
  '/fuel': typeof FuelRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/signup': typeof SignupRoute
  '/trips': typeof TripsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/drivers': typeof DriversRoute
  '/fleet': typeof FleetRoute
  '/fuel': typeof FuelRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/signup': typeof SignupRoute
  '/trips': typeof TripsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/drivers'
    | '/fleet'
    | '/fuel'
    | '/login'
    | '/maintenance'
    | '/signup'
    | '/trips'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/drivers'
    | '/fleet'
    | '/fuel'
    | '/login'
    | '/maintenance'
    | '/signup'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/drivers'
    | '/fleet'
    | '/fuel'
    | '/login'
    | '/maintenance'
    | '/signup'
    | '/trips'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  DriversRoute: typeof DriversRoute
  FleetRoute: typeof FleetRoute
  FuelRoute: typeof FuelRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  SignupRoute: typeof SignupRoute
  TripsRoute: typeof TripsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuel': {
      id: '/fuel'
      path: '/fuel'
      fullPath: '/fuel'
      preLoaderRoute: typeof FuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  DriversRoute: DriversRoute,
  FleetRoute: FleetRoute,
  FuelRoute: FuelRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  SignupRoute: SignupRoute,
  TripsRoute: TripsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
